# Generated by Django 4.0.1 on 2022-01-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nam',
        ),
    ]
